### ISSUE TITLE
Line Difference Coloring does NOT work in release 134

### ISSUE THREAD

**Issue by wangyugui** [sdottaka/winmerge-v2#28]
Line Difference Coloring(both char level and word level) does NOT work in release 134, but it is OK in release 129.
<img width="1280" alt="no-diff-color" src="https://cloud.githubusercontent.com/assets/13562993/26345169/a0ca787e-3fd4-11e7-9266-73ceda8016d2.png">

**Comment by sdottaka** [comment]
Thank you for the report.
I've fixed it and uploaded a new release.

**Comment by wangyugui** [comment]
It is fixed in my environment too.
Thanks a lot for your job.
