### ISSUE TITLE
Build requirements?

### ISSUE THREAD

**Issue by cryham** [sdottaka/winmerge-v2#30]
Hi.
What is the minimum VS version that can build the project?
I have access only to VS 2008 and 2010.
Is it possible to build with them? Or did you already use language features from above.
It was possible with the old WinMerge.

**Comment by sdottaka** [comment]
The version of Visua lStudio that can build this fork is Visual Studio 2015 or 2017.
I am using Visual Studio Community 2017.

**Comment by cryham** [comment]
Thanks. I got the VS Community 2017 installed. Works fine now.
I see 2 errors (below). Probably not important, works anyway, but pasted to report them.
I'm guessing some wrong relative paths to tools or something.

Error		Can not find script file "C:\w\7-repo^\7 wmrg-j\Src\UpdatePoFilesFromPotFile.vbs".	MergeLang	C:\w\7-repo^\7 wmrg-j\Src\EXEC	1	

Error	 MSB3073	The command "pushd C:\w\7-repo^\7 wmrg-j\Src\..\Translations\WinMerge
cscript UpdatePoFilesFromPotFile.vbs
popd
mkdir .\..\Build\MergeUnicodeDebug\\Languages\ 2> NUL
copy /Y "C:\w\7-repo^\7 wmrg-j\Src\..\Translations\WinMerge\*.po" ".\..\Build\MergeUnicodeDebug\\Languages\"
:VCEnd" exited with code -1.	MergeLang	C:\Program Files (x86)\Microsoft Visual Studio 2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	133

**Comment by sdottaka** [comment]
After placing the source code in C:\w\7-repo^\7 wmrg-j, I could reproduce the error.
If the folder name "7-repo^" is changed to "7-repo", error will not occur.

**Comment by cryham** [comment]
Ah wow, so VS doesn't like the ^ symbol in paths. Thanks for finding it out.
