### ISSUE TITLE
new files PropMarkerColors (.h and .cpp) missing in jp-138 release

### ISSUE THREAD

**Issue by GreyMerlin** [sdottaka/winmerge-v2#35]
HI ... the two new (and WIP) files `PropMarkerColors.h` and `PropMarkerColors.cpp` are missing from this newest **jp-138** release.  The `PropMarkerColors.h` file is referenced at `PreferencesDlg.h` (21).  And the `.vcxproj` file shows that both files are necessary for the compile.  This WIP is from commit "_editlib: Implement Marker feature (WIP)_" c1d66d6e43240c682f652e532abc5fb1e208b72b.  (These are the only two files that I noticed that are missing.) Therefore WinMerge cannot compile successfully ...

See also **Pull #36**, which is related, but different.

Thanks !!

**Comment by sdottaka** [comment]
Thank you for your report. Fixed by 3d4370970f974de8bf6bb67b3bcc669c4316dd26

**Comment by GreyMerlin** [comment]
**Thanks !!**  I look forward to the completed Marker feature !!
