### ISSUE TITLE
New Files ctextmarkerdlg.h and ctextmarkerdlg.cpp are missing !?

### ISSUE THREAD

**Issue by GreyMerlin** [sdottaka/winmerge-v2#40]
The repo (here and at BitBucket) seems to be missing the files `ctextmarkerdlg.h` and `ctextmarkerdlg.cpp` (and perhaps others?).  These are new files with version **2.14.0+-jp141**, commit "**_editlib: Implement Marker feature(2)_**".  WinMerge no longer compiles :(

**Comment by sdottaka** [comment]
Sorry again. I've committed the files.

**Comment by GreyMerlin** [comment]
No Worries !! THANKS !!
