### ISSUE TITLE
WinMerge 2011? Kimmo Varis validated?

### ISSUE THREAD

**Issue by Neustradamus** [sdottaka/winmerge-v2#41]
Good news to see this github!

This project is same that WinMerge 2011?
https://bitbucket.org/jtuc/winmerge2011/
https://bitbucket.org/jtuc/winmerge2011/commits/

It is Kimmo Varis (...) validated?

**Comment by gerundt** [comment]
WinMerge 2011 is a fork from *Jochen Tucht*. This Version can run with Wine even under Linux!

Kimmo Varis is not active the last years.

**Comment by sdottaka** [comment]
Thank you for the clarification.

**Comment by Neustradamus** [comment]
It is not possible to have one team?
@sdottaka and jtuc
