### ISSUE TITLE
HighDPI support

### ISSUE THREAD

**Issue by beru** [sdottaka/winmerge-v2#54]
Some of UI elements are displayed too small with HighDPI envrionment.
I use Version 2.14.0.80+-jp-80. 

Please look at below pictures.

![image](https://user-images.githubusercontent.com/1131125/35341399-f01511c2-0168-11e8-8477-fef929fb1082.png)

* Font size of  Location Pane window caption text is too small compared to other UI elements.
* Diff Pane window caption text is also too small

![image](https://user-images.githubusercontent.com/1131125/35341686-9dd8e6ee-0169-11e8-8b98-546d18d4a201.png)
* Width of status bar panel is too short, so the text (in this case, 3個の差異が見…られます？) is not fully displayed. 

![image](https://user-images.githubusercontent.com/1131125/35341982-4399424a-016a-11e8-9b02-0201ab09d8bc.png)

* MDI window's minimize-maximize-close icons look very big with above screenshot but once you maximize the window, those icons are displayed at the right side of menu items and icons are somewhat small.

**Comment by sdottaka** [comment]
Thank you for the report.
I will try to fix these problems.
But I'm not sure that the last problem is fixable since these icons are drawn by Windows.
