### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by beru** [sdottaka/winmerge-v2#55]
https://github.com/sdottaka/winmerge-v2/blob/694237ae888703115145eaf100369d286c8c5e1b/Src/Common/scbarcf.cpp#L104

I've tried to build Merge project after cloning the repositry and encountered this error with Release Unicode x64 build. I use Visual Studio Version 15.5.5.
```
4>Common\scbarcf.cpp(105): error C2143: syntax error: missing ';' before '}'
```

master branch Head SHA-1 694237ae888703115145eaf100369d286c8c5e1b

**Comment by sdottaka** [comment]
Oops! Thank you for the report. Fixed in 353a745e47d5df379b90c674115474d02dfd7c13
