### ISSUE TITLE
Picture compare - show "files are identical" in statusbar

### ISSUE THREAD

**Issue by ganego** [sdottaka/winmerge-v2#63]
Right now, when two pictures are the same, you will get a messagebox telling you this. There you can disable this message box (see picture).  

Problem:
- Having a box you have to close each time is annoying
- But when the box is disabled, you have no quick way to see this information if both pictures are identical.

Solution:
- Give the information that the pictures are identical always also in the statusbar.
See pic: https://imgur.com/a/9kFBR of how this could look like.

Thank you

**Comment by sdottaka** [comment]
on my PC, WinMerge shows "Identical" in the statusbar as follows:

<img width="640" alt="idential" src="https://user-images.githubusercontent.com/98126/35831618-ade02478-0b0d-11e8-986c-bb0b81926b27.png">

Do not you see it in your environment?

**Comment by ganego** [comment]
I must have been really blind. Yes it does show up. Sorry.
