### ISSUE TITLE
Drag'n'Drop with phantom characters

### ISSUE THREAD

**Issue by oezgueremir** [sdottaka/winmerge-v2#75]
When using Drag'n'Drop to external programs, the second item has often additional characters, which don't belong to the filename. Missing terminating zero?

![screenshot](https://user-images.githubusercontent.com/5089754/36586728-1c068406-1883-11e8-9042-f6b8006a92f6.png)

**Comment by sdottaka** [comment]
Could you try it with the latest version?

I think the following commit fixes this problem.

https://github.com/sdottaka/winmerge-v2/commit/4e1686a6ffd4d5fba22cfbb1dfc9e538aebcf698

**Comment by oezgueremir** [comment]
Hi!
My bad, forgot to mention the version...

I think, this bug turned out here on my machine with WinMerge-2.14.0-jp-144.
It was sill there with WinMerge-2.14.0-jp-147, since I did the screenshots and testing with this version.

I just downloaded WinMerge-2.14.0-jp-148.
If the bug still shows up, I will come back to you

**Comment by sdottaka** [comment]
Now I can reproduce this bug with Notepad2, Notepad2-mod, and AkelPad.
But I cannot reproduce this bug with Notepad++, Excel, Word, and VisualStudio2017.

Probably the cause of the problem is that the file paths copied to the clipboard are not terminated with NUL characters.

However, if you terminate with NUL characters, it seems that another problem may occur depending on the editor. It may be a difficult problem.

**Comment by oezgueremir** [comment]
Do you actually get any problems in other editors, or is your argument based on a suspicion?
Since the old implemention explicitly added a termination zero, where there any reported issues on that?

I could have live with this issue, if it would only be my text editor, and I just have to press backspace several times. But actually I am using drag'n'drop to another application, so the handling is not very comfortable.

**Comment by sdottaka** [comment]
I have forgotten why I fixed the NUL termination removed.
I think it was a wrong fix.

So I have uploaded version 2.14.0+-jp-149 that fixes this issue.

**Comment by oezgueremir** [comment]
Cool, thank you!

Just installed it and already worked with it (~30 files).
The issue didn't happen so far...
